import { StyleSheet } from 'react-native';
import { THEME } from '../../assets/styles/theme';

const styles = StyleSheet.create({
  container: { flex: 1, },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f4f6fb',
  },
  bakcgroundImage: {
    flex: 1,
    justifyContent: 'center',
    height: '100%',
  },
  header: {
    backgroundColor: '#2a2c40',
    elevation: 0,
    shadowOpacity: 0,
    borderBottomWidth: 0,
    paddingVertical: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
  },
  headerTitle: {
    color: THEME.COLOR.textWhite,
    fontSize: 18,
    fontFamily: 'DMSans-Medium',
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
  },

  backBtn: {
    marginRight: 15,
    width: 45,
    height: 45,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 100,
  },
  scrollContent: { padding: 16, paddingBottom: 24 },

  sectionCard: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 14,
    padding: 16,
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#fff',
    marginBottom: 14,
    letterSpacing: 0.3,
  },

  orderItem: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.2)',
    paddingVertical: 10
  },
  orderItemImage: {
    width: 52,
    height: 52,
    borderRadius: 10,
    backgroundColor: '#f0f4ff',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    marginRight: 12,
    padding: 5
  },
  itemEmoji: { fontSize: 22 },
  orderItemInfo: { flex: 1, marginRight: 8 },
  orderItemName: {
    fontSize: 13,
    fontWeight: '500',
    color: '#fff',
    lineHeight: 18,
  },
  orderItemMeta: { fontSize: 12, color: '#fff', marginTop: 3 },
  orderItemPoints: {
    width: 52,
    height: 52,
    borderRadius: 10,
    backgroundColor: '#f0f4ff',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  orderItemScore: { fontSize: 15, fontWeight: '700', color: '#000' },
  orderItemScoreLabel: { fontSize: 11, color: '#000' },

  divider: { height: 1, backgroundColor: '#eef0f4', marginVertical: 10 },

  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 6,
  },
  summaryLabel: { fontSize: 14, color: '#fff' },
  summaryValue: { fontSize: 15, fontWeight: '600', color: '#fff' },
  totalPointsText: { color: '#fff', fontSize: 15, fontWeight: '700' },

  inputGroup: { marginBottom: 12 },
  inputLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#fff',
    marginBottom: 5,
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  inputContainer: {
    borderRadius: THEME.RADIUS.large,
    height: 50,
    width: '100%',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: 'rgba(255, 255, 255, 0.4)'
  },
  textInput: {
    height: 50,
    width: '100%',
    paddingHorizontal: 15,
    fontSize:14,
    color: '#fff',
    fontFamily: THEME.FONTWEIGHT.Regular,
  },
  // Red border when field has an error
  textInputError: {
    borderColor: '#e74c3c',
  },
  // Inline error message below the field
  errorText: {
    fontSize: 12,
    color: '#fff',
    marginTop: 10,
    marginLeft: 6,
  },
  rowInputs: { flexDirection: 'row' },

  pointsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 2,
  },
  pointsRowLabel: { fontSize: 13, color: '#fff' },
  pointsRowValue: { fontSize: 13, fontWeight: '600', color: '#fff' },

  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: '#eef0f4',
    elevation: 10,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: -3 },
    shadowRadius: 8,
  },
  footerInfo: { flex: 1, marginRight: 12 },
  footerPoints: { fontSize: 18, fontWeight: '800', color: '#000' },
  footerItemCount: { fontSize: 12, color: '#8892a4', marginTop: 1 },
  placeOrderBtn: {
    backgroundColor: THEME.COLOR.bgPurple,
    paddingHorizontal: 28,
    paddingVertical: 14,
    borderRadius: 12,
    minWidth: 140,
    alignItems: 'center',
    elevation: 3,
    shadowColor: THEME.COLOR.bgPurple,
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
  },
  placeOrderBtnDisabled: { opacity: 0.6 },
  placeOrderText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.3,
  },

  successContainer: { flex: 1, backgroundColor: '#0a3d62' },
  successContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  successIconWrapper: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: '#27ae60',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
    elevation: 6,
    shadowColor: '#27ae60',
    shadowOpacity: 0.4,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
  },
  successIconText: { fontSize: 40, color: '#fff', fontWeight: '700' },
  successTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: '#fff',
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  successSubtitle: {
    fontSize: 14,
    color: '#a8c8e8',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 28,
  },
  orderIdBadge: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 10,
    paddingHorizontal: 20,
    paddingVertical: 10,
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  orderIdLabel: {
    fontSize: 11,
    color: '#a8c8e8',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  orderIdValue: {
    fontSize: 18,
    fontWeight: '700',
    color: '#fff',
    marginTop: 2,
  },
  continueShopping: {
    backgroundColor: '#2874f0',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 32,
    width: '100%',
    alignItems: 'center',
    marginBottom: 12,
  },
  continueShoppingText: { color: '#fff', fontSize: 15, fontWeight: '700' },
  viewOrders: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 32,
    width: '100%',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  viewOrdersText: { color: '#fff', fontSize: 15, fontWeight: '600' },
});

export default styles;
